name: Workflow1
on: [push, workflow_dispatch]
 jobs:
  deploy:
   run-on: ubuntu-latest
   steps:
    -name: get code
     uses: action/checkout@4
    -name: install dependencies
     run: npm ci
    -name: build code
     run: echo "build code"
